# https://rust-lang.github.io/rustfmt/
hard_tabs = false
tab_spaces = 2
trailing_comma = "Always"
color = "Always"
empty_item_single_line = true
normalize_doc_attributes = true
trailing_semicolon = true
comment_width = 90
wrap_comments = true
format_code_in_doc_comments = true

force_explicit_abi = true
format_strings = true

# width
max_width = 90
# https://rust-lang.github.io/rustfmt/?version=v1.4.38&search=#use_small_heuristics
# chain_width = 60
# fn_call_width = 60

# function
fn_args_layout = "Vertical"
fn_single_line = true

# imports
imports_indent = "Visual"
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = false

# modules
reorder_modules = false
